name: nearby
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_splash_screen: ^1.0.0+1
  flushbar: ^1.10.4
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2+1
  firebase_messaging: ^6.0.16
  awesome_dialog: ^1.1.3
  animator: ^1.0.0+5
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.11
  photo_manager: ^0.5.7
  image_picker: ^0.6.7+4
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.17
  location: ^3.0.2
  simple_image_crop: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  video_player: ^0.10.11+2
  photo_view: ^0.9.2
  giphy_picker: 
    path: ./lib/modified_lib/giphy_picker-1.0.4
  video_trimmer: ^0.2.6
  timeago: ^2.0.26
  uuid: ^2.2.0
  flutter_video_compress: ^0.3.7+8
  date_picker_timeline: ^1.2.0
  

dev_dependencies:
  
  flutter_launcher_icons: ^0.7.5
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/profilephoto.png
    - assets/resturant_back.png
    - assets/vehi_back.png
    - assets/events_back.png
    - assets/apparel_back.jpg
    - assets/night_life_back.jpg
    - assets/education_back.jpg
    - assets/stay_back.jpg
    - assets/groc_back.jpg
    - assets/place_background.png
    
    - assets/icons/eye_open.png
    - assets/icons/eye_close.png
    - assets/icons/bell.png
    - assets/icons/chat.png
    - assets/icons/user.png
    - assets/icons/home.png
    - assets/icons/plus.png
    - assets/icons/resturant.png
    - assets/icons/hotel.png
    - assets/icons/bar.png
    - assets/icons/events.png
    - assets/icons/grocery.png
    - assets/icons/place.png
    - assets/icons/vehicle.png
    - assets/icons/tution.png
    - assets/icons/apparel.png
    - assets/icons/constru.png
    - assets/icons/salon.png
    - assets/icons/electronics.png
    - assets/icons/left-arrow.png
    - assets/icons/forward.png
    - assets/icons/done.png
    - assets/icons/camera.png
    - assets/icons/video-camera.png
    - assets/icons/dot.png
    - assets/icons/dining.png
    - assets/icons/takeaway.png
    - assets/icons/delivery.png
    - assets/icons/anyFoodType.png
    - assets/icons/cut.png
    - assets/icons/crop.png
    - assets/icons/foodmenu.png
    - assets/icons/album.png
    - assets/icons/hotdishes.png
    - assets/icons/meat.png
    - assets/icons/vegetarian.png
    - assets/icons/drink.png
    - assets/icons/fast-food.png
    - assets/icons/desserts.png
    - assets/icons/add.png
    - assets/icons/close.png
    - assets/icons/play.png
    - assets/icons/property.png
    - assets/icons/furniture.png
    - assets/icons/beach.png
    - assets/icons/agri.png
    - assets/icons/botnical_gardens.png
    - assets/icons/dive.png
    - assets/icons/forest.png
    - assets/icons/hike.png
    - assets/icons/historical.png
    - assets/icons/local.png
    - assets/icons/meditaion.png
    - assets/icons/mountain.png
    - assets/icons/museum.png
    - assets/icons/national-park.png
    - assets/icons/river.png
    - assets/icons/temple.png
    - assets/icons/theme-park.png
    - assets/icons/trees.png
    - assets/icons/zoo.png
    
    - assets/icons/baby_products.png
    - assets/icons/bread.png
    - assets/icons/canned-food.png
    - assets/icons/detergent.png
    - assets/icons/flour.png
    - assets/icons/ice-cream.png
    - assets/icons/medicine.png
    - assets/icons/milk.png
    - assets/icons/soap.png
    - assets/icons/toilet-paper.png
    - assets/icons/vegetable.png
    - assets/icons/beverages.png
    - assets/icons/meatgroc.png
    
    - assets/icons/award.png
    - assets/icons/cleanup.png
    - assets/icons/conference.png
    - assets/icons/help.png
    - assets/icons/launch.png
    - assets/icons/meetup.png
    - assets/icons/music.png
    - assets/icons/parties.png
    - assets/icons/seminar.png
    - assets/icons/sports.png
    - assets/icons/tradeshow.png
    - assets/icons/workshop.png
    
    - assets/icons/bag.png
    - assets/icons/belt.png
    - assets/icons/cufflinks.png
    - assets/icons/dress.png
    - assets/icons/tops.png
    - assets/icons/jacket.png
    - assets/icons/jewellery.png
    - assets/icons/sneaker.png
    - assets/icons/sunglasses.png
    - assets/icons/ladies_wallet.png
    - assets/icons/tie.png
    - assets/icons/ladies_hat.png
    - assets/icons/watch.png
    - assets/icons/pant.png
    - assets/icons/cap.png
    - assets/icons/skirt.png
    - assets/icons/socks.png
    - assets/icons/sports_wear.png
    - assets/icons/blouse.png
    - assets/icons/toys.png
    - assets/icons/polo_shirt.png
    - assets/icons/round_neck.png
    - assets/icons/v_neck.png
    - assets/icons/girls_pant.png
    - assets/icons/female_denim.png
    - assets/icons/joggers.png
    - assets/icons/female_shirt.png
    - assets/icons/saree1.png
    - assets/icons/kurti.png
    - assets/icons/over_coat.png
    - assets/icons/female_shoe.png
    - assets/icons/female_slipper.png
    - assets/icons/sleepwear.png
    - assets/icons/bra.png
    - assets/icons/panties.png
    - assets/icons/frock.png
    - assets/icons/wallet.png
    - assets/icons/shawl.png
    - assets/icons/hair_Acc.png
    - assets/icons/casual_shirt.png
    - assets/icons/fashion.png
    - assets/icons/short.png
    - assets/icons/hoodie.png
    - assets/icons/kurta.png
    - assets/icons/sneaker.png
    - assets/icons/slippers.png
    - assets/icons/underwear.png
    - assets/icons/boy_bag.png
    - assets/icons/bag_pack.png
    - assets/icons/seafood.png
    - assets/icons/spare_parts.png
    - assets/icons/sell_car.png
    - assets/icons/cabs.png
    - assets/icons/car_hire.png
    - assets/icons/service_center.png
    - assets/icons/rent_car.png
    - assets/icons/tyre.png
    - assets/icons/repair.png
    - assets/icons/engine_repair.png
    - assets/icons/engine_tune.png
    - assets/icons/suspension.png
    - assets/icons/breaking.png
    - assets/icons/car_audio_modify.png
    - assets/icons/interio_modify.png
    - assets/icons/exterio_modify.png
    - assets/icons/safety_modify.png
    - assets/icons/lights_modify.png
    - assets/icons/paint_modify.png
    - assets/icons/car_stickers.png
    - assets/icons/offroad_modify.png
    - assets/icons/air-conditioning.png
    - assets/icons/hybrid.png
    - assets/icons/electric.png
    - assets/icons/none.png
    - assets/icons/bus.png
    - assets/icons/excavator.png
    - assets/icons/heavytruck.png
    - assets/icons/motorcycle.png
    - assets/icons/lorry.png
    - assets/icons/rickshaw.png
    - assets/icons/hire.png
    - assets/icons/night_club.png
    - assets/icons/festival.png
    - assets/icons/live_music.png
    - assets/icons/pub.png
    - assets/icons/night_Rest.png
    - assets/icons/cafe.png
    - assets/icons/_night_bar.png
    - assets/icons/air-conditioner.png
    - assets/icons/bath_tub.png
    - assets/icons/bbq.png
    - assets/icons/bike.png
    - assets/icons/billiard-ball.png
    - assets/icons/cooking.png
    - assets/icons/garden.png
    - assets/icons/gym.png
    - assets/icons/heating.png
    - assets/icons/iorn_board.png
    - assets/icons/kitchen.png
    - assets/icons/laundery.png
    - assets/icons/microwave.png
    - assets/icons/pool.png
    - assets/icons/refrigerator.png
    - assets/icons/shower.png
    - assets/icons/spa.png
    - assets/icons/television.png
    - assets/icons/wifi.png
    - assets/icons/parking.png
    - assets/icons/other.png
    
    - assets/json/services.json
    - assets/json/sell_vehi.json
    - assets/json/stay_features.json
    - assets/json/night_life.json
    - assets/json/map_style.json
    - assets/json/rent_types.json
    - assets/json/vehi_services.json
    - assets/json/event_type.json
    - assets/json/food_menu.json
    - assets/json/grocery_item_types.json
    - assets/json/place_categories.json
    - assets/json/apparel/boys's wear.json
    - assets/json/apparel/men's wear.json
    - assets/json/apparel/women's wear.json
    - assets/json/customize_repair/vehi_modie.json
    - assets/json/customize_repair/vehi_tech.json
    - assets/json/customize_repair/vehi_types.json

  