name: nearby
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_splash_screen: ^1.0.0+1
  flushbar: ^1.10.4
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  progress_dialog: ^1.2.4
  flutter_spinkit: ^4.1.2+1
  firebase_messaging: ^6.0.16
  awesome_dialog: ^1.1.3
  animator: ^1.0.0+5
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.11
  photo_manager: ^0.5.7
  image_picker: ^0.6.7+4
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  google_maps_webservice: ^0.0.17
  location: ^3.0.2
  simple_image_crop: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  video_player: ^0.10.11+2
  photo_view: ^0.9.2
  giphy_picker: 
    path: ./lib/modified_lib/giphy_picker-1.0.4
  video_trimmer: ^0.2.6
  timeago: ^2.0.26
  uuid: ^2.2.0
  flutter_video_compress: ^0.3.7+8
  

dev_dependencies:
  
  flutter_launcher_icons: ^0.7.5
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/profilephoto.png
    - assets/resturant_back.png
    - assets/groc_back.jpg
    - assets/place_background.png
    
    - assets/icons/eye_open.png
    - assets/icons/eye_close.png
    - assets/icons/bell.png
    - assets/icons/chat.png
    - assets/icons/user.png
    - assets/icons/home.png
    - assets/icons/plus.png
    - assets/icons/resturant.png
    - assets/icons/hotel.png
    - assets/icons/bar.png
    - assets/icons/events.png
    - assets/icons/grocery.png
    - assets/icons/place.png
    - assets/icons/vehicle.png
    - assets/icons/tution.png
    - assets/icons/apparel.png
    - assets/icons/constru.png
    - assets/icons/salon.png
    - assets/icons/electronics.png
    - assets/icons/left-arrow.png
    - assets/icons/forward.png
    - assets/icons/done.png
    - assets/icons/camera.png
    - assets/icons/video-camera.png
    - assets/icons/dot.png
    - assets/icons/dining.png
    - assets/icons/takeaway.png
    - assets/icons/delivery.png
    - assets/icons/anyFoodType.png
    - assets/icons/cut.png
    - assets/icons/crop.png
    - assets/icons/foodmenu.png
    - assets/icons/album.png
    - assets/icons/hotdishes.png
    - assets/icons/meat.png
    - assets/icons/vegetarian.png
    - assets/icons/drink.png
    - assets/icons/fast-food.png
    - assets/icons/desserts.png
    - assets/icons/add.png
    - assets/icons/close.png
    - assets/icons/play.png
    - assets/icons/property.png
    - assets/icons/furniture.png
    - assets/icons/beach.png
    - assets/icons/agri.png
    - assets/icons/botnical_gardens.png
    - assets/icons/dive.png
    - assets/icons/forest.png
    - assets/icons/hike.png
    - assets/icons/historical.png
    - assets/icons/local.png
    - assets/icons/meditaion.png
    - assets/icons/mountain.png
    - assets/icons/museum.png
    - assets/icons/national-park.png
    - assets/icons/river.png
    - assets/icons/temple.png
    - assets/icons/theme-park.png
    - assets/icons/trees.png
    - assets/icons/zoo.png
    
    - assets/icons/baby_products.png
    - assets/icons/bread.png
    - assets/icons/canned-food.png
    - assets/icons/detergent.png
    - assets/icons/flour.png
    - assets/icons/ice-cream.png
    - assets/icons/medicine.png
    - assets/icons/milk.png
    - assets/icons/soap.png
    - assets/icons/toilet-paper.png
    - assets/icons/vegetable.png
    - assets/icons/beverages.png
    - assets/icons/meatgroc.png
    
    - assets/json/services.json
    - assets/json/map_style.json
    - assets/json/grocery_item_types.json
    - assets/json/place_categories.json

  